variable vpc_cidr_block {}
variable  subnet_main_public_1_cidr_block {} 
variable  subnet_main_public_2_cidr_block {} 
variable  subnet_main_public_3_cidr_block {} 
variable  subnet_main_private_1_cidr_block {}
variable  subnet_main_private_2_cidr_block {} 
variable  subnet_main_private_3_cidr_block {} 
variable avail_zone1 {}
variable avail_zone2 {}
variable avail_zone3 {}
variable my_ip {}
variable env_prefix {}
variable image_name {}
variable public_key_location {}
variable instance_type1 {}
variable RDS_USERNAME {}
variable RDS_PASSWORD {}