variable vpc_id {}
variable subnet_main_private_1 {}
variable subnet_main_private_2 {}
variable subnet_main_public_1 {}
variable subnet_main_public_2 {}
variable aws_db_instance {}
variable key_pair {}
variable instance_type1 {}
variable env_prefix {}
